### ISSUE TITLE
update 0.13?

### ISSUE THREAD

**Issue by Goten87** [dkaisers/filtered-deconstruction-planner#1]
are u updating to 0.13 anytime soon and upload it to modportal ?

**Comment by dkaisers** [comment]
0.13 was published basically at the same time my master's degree's exam period started, so I'll get on it as soon as that ends on Wednesday.

**Comment by dkaisers** [comment]
Thanks to @Choumiko the mod is now compatible with 0.13 and will be released to the mod portal asap after I updated the icon style of the item.
