### ISSUE TITLE
Tiles not filterable

### ISSUE THREAD

**Issue by dkaisers** [dkaisers/filtered-deconstruction-planner#3]
It is neither possible to select tiles as filter using the "eyedropper mode", nor is it possible to use the _target_ and _exclude_ modes on tiles after they are added to the filter configuration manually.

**Comment by Choumiko** [comment]
You might want to look at the new events for when an area is selected:
https://github.com/Choumiko/ModuleInserter/blob/master/control.lua#L237
or add any_tile to the selection_mode in the items definition, valid modes: https://github.com/Choumiko/ModuleInserter/blob/master/prototypes/item.lua#L18 (haven't tried whether they are changeable at runtime)

**Comment by dkaisers** [comment]
Thanks, I'll check it out. Apparently I excluded _deconstructible-tile-proxy_ entities from being able to mark in modes other than _normal_ for reasons that I can't recall, but I think it will be probably possible to filter them in a similar manner like the _item-on-ground_ proxies.
